### ISSUE TITLE
Sometime pylint change rule names and it crash :'(

### ISSUE THREAD

**Issue by louisjdmartin** [omegacen/pylint-sonarjson#3]
Hi,

We have discover that pylint changes their "message id" sometimes and so your plugin may crash on pylint upgrade.
For exemple: [C0122 was changed to C2201](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/old-misplaced-comparison-constant.html)
You can see this kind of stacktrace:
```
Traceback (most recent call last):
  File "/home/mp/martilo/demoddc/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/mp/martilo/demoddc/lib/python3.7/site-packages/pylint/__init__.py", line 25, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/home/mp/martilo/demoddc/lib/python3.7/site-packages/pylint/lint/run.py", line 159, in __init__
    linter, args, reporter, config_file=self._rcfile, verbose_mode=self.verbose
  File "/home/mp/martilo/demoddc/lib/python3.7/site-packages/pylint/config/config_initialization.py", line 102, in _config_initialization
    linter.load_plugin_configuration()
  File "/home/mp/martilo/demoddc/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 380, in load_plugin_configuration
    module.load_configuration(self)
  File "/home/mp/martilo/demoddc/lib/python3.7/site-packages/pylint_sonarjson/__init__.py", line 25, in load_configuration
    sonar_checker.load_configuration()
  File "/home/mp/martilo/demoddc/lib/python3.7/site-packages/pylint_sonarjson/sonaroptions_checker.py", line 103, in load_configuration
    self._parse_sonar_rule(sonar_rule)
  File "/home/mp/martilo/demoddc/lib/python3.7/site-packages/pylint_sonarjson/sonaroptions_checker.py", line 109, in _parse_sonar_rule
    msg_id = self._validate_msg_id(split[0])
  File "/home/mp/martilo/demoddc/lib/python3.7/site-packages/pylint_sonarjson/sonaroptions_checker.py", line 134, in _validate_msg_id
    raise InvalidArgsError(f"{msg_id} is not a known message id.")
pylint.exceptions.InvalidArgsError: C0326 is not a known message id.
```

For various reason, we want it to "work" even if message id does not exist.
Depending on how your code works, do you think it's possible to prevent crash and replace it with warning somewhere ? Or maybe by adding an option to CLI to ignore theses errors ?

It will help our team by giving more time to quality managers to provides new configuration files on pylint upgrades (that includes new pylint IDs) without blocking CI and other builds.

Thanks for your help

**Comment by louisjdmartin** [comment]
I forgot to put pylintrc...
Here a configuration that generates the error (pylint==2.14.3)
```
[REMOVED CODE]
load-plugins=cnes_checker,pylint.extensions.check_elif,pylint_sonarjson
[REMOVED CODE]
disable=all
enable=R5104,W0703,R5402,R5401,R5105,R0203,R0204,R5403,R5106,R0401,W0102,W9097,E0108,R5103,F0002,W9096,C0204,C0203,E0213,C0122,W9095,W0312,W0406,R5101,W0622,W0621,W0404,W0403,R5201,R5301,R5302,R5102,R0915,W0602,E0602,C0412,W0612,C0113,W0603,E0601,C0411,C0413,C0326
[REMOVED CODE]
sonar-rules=C0113:MINOR:10:CODE_SMELL,C0122:MINOR:10:CODE_SMELL,C0203:MINOR:10:CODE_SMELL,C0204:MINOR:10:CODE_SMELL,C0326:MINOR:10:CODE_SMELL,C0411:MINOR:10:CODE_SMELL,C0412:MINOR:10:CODE_SMELL,C0413:MINOR:10:CODE_SMELL,E0108:MINOR:10:CODE_SMELL,E0213:MAJOR:10:CODE_SMELL,E0601:MAJOR:10:CODE_SMELL,E0602:MAJOR:10:CODE_SMELL,F0002:MAJOR:10:CODE_SMELL,R0203:MINOR:10:CODE_SMELL,R0204:CRITICAL:10:CODE_SMELL,R0401:MINOR:10:CODE_SMELL,R0915:MINOR:10:CODE_SMELL,R5101:CRITICAL:10:CODE_SMELL,R5102:CRITICAL:10:CODE_SMELL,R5103:CRITICAL:10:CODE_SMELL,R5104:CRITICAL:10:CODE_SMELL,R5105:CRITICAL:10:CODE_SMELL,R5106:CRITICAL:10:CODE_SMELL,R5201:CRITICAL:10:CODE_SMELL,R5301:CRITICAL:10:CODE_SMELL,R5302:CRITICAL:10:CODE_SMELL,R5401:BLOCKER:10:CODE_SMELL,R5402:BLOCKER:10:CODE_SMELL,R5403:BLOCKER:10:CODE_SMELL,W0102:MINOR:10:CODE_SMELL,W0312:MAJOR:10:CODE_SMELL,W0403:MINOR:10:CODE_SMELL,W0404:MINOR:10:CODE_SMELL,W0406:MINOR:10:CODE_SMELL,W0602:MINOR:10:CODE_SMELL,W0603:MINOR:10:CODE_SMELL,W0612:MINOR:10:CODE_SMELL,W0621:MINOR:10:CODE_SMELL,W0622:MINOR:10:CODE_SMELL,W0703:MINOR:10:CODE_SMELL,W9095:CRITICAL:10:CODE_SMELL,W9096:CRITICAL:10:CODE_SMELL,W9097:CRITICAL:10:CODE_SMELL
output-format=sonarjson
```

**Comment by teake** [comment]
Hi, thanks for the report. I'm not sure I understand the use case here -- personally I pin the version of Pylint that's used in our CI pipelines. If there's a Pylint rule / message that I want enabled but doesn't exist, I don't want the pipeline to silently ignore it.

But I can see CLI switch being useful in other situations, so I added `--halt-on-invalid-sonar-rules` in version 1.0.4, which should do what you want. Setting this to `n` will only report the missing rules on stderr and otherwise ignore them. Not sure how you'll pick that up in your CI pipeline though ...

**Comment by louisjdmartin** [comment]
Hi,
Our use case is pretty strange in fact. I'm not sure that I can explain it correctly, but your fix will do exactly what we need. I also see in git diff that you send useful logs in `stderr`, that's great for us to keep track of ignored rules.

Thanks for your help.
